//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SavesManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SavesManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This program is for backup and restoring saves files from the games. It is designed for those who often reinstall Windows and get tired of manually backing up all the saves or losing them. All info about your games is stored in &quot;storage.dat&quot;. Feel free to edit this file in case some of your paths has been changed.
        ///
        ///© 2022. Kornienko Dev.
        /// </summary>
        public static string about_text {
            get {
                return ResourceManager.GetString("about_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string about_window_name {
            get {
                return ResourceManager.GetString("about_window_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new game.
        /// </summary>
        public static string add_game {
            get {
                return ResourceManager.GetString("add_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Game name:.
        /// </summary>
        public static string add_game_name {
            get {
                return ResourceManager.GetString("add_game_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saves path:.
        /// </summary>
        public static string add_game_path {
            get {
                return ResourceManager.GetString("add_game_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new game.
        /// </summary>
        public static string add_game_window {
            get {
                return ResourceManager.GetString("add_game_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Backup.
        /// </summary>
        public static string backup {
            get {
                return ResourceManager.GetString("backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Backup all.
        /// </summary>
        public static string backup_all {
            get {
                return ResourceManager.GetString("backup_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please choose a game..
        /// </summary>
        public static string choose_game {
            get {
                return ResourceManager.GetString("choose_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Please click to choose game image.).
        /// </summary>
        public static string choose_image {
            get {
                return ResourceManager.GetString("choose_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you really want to backup ALL saves?
        ///(only the new files will be overwritten).
        /// </summary>
        public static string doYouWantToBackup {
            get {
                return ResourceManager.GetString("doYouWantToBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you really want to delete .
        /// </summary>
        public static string doYouWantToDelete {
            get {
                return ResourceManager.GetString("doYouWantToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you really want to restore ALL saves?
        ///(only the new files will be overwritten).
        /// </summary>
        public static string doYouWantToRestore {
            get {
                return ResourceManager.GetString("doYouWantToRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty game list..
        /// </summary>
        public static string empty_game_list {
            get {
                return ResourceManager.GetString("empty_game_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter game name and game path..
        /// </summary>
        public static string enter_game_data {
            get {
                return ResourceManager.GetString("enter_game_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Files are synced..
        /// </summary>
        public static string filesAreSynced {
            get {
                return ResourceManager.GetString("filesAreSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Game is already in the list..
        /// </summary>
        public static string game_in_list {
            get {
                return ResourceManager.GetString("game_in_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Game information.
        /// </summary>
        public static string game_information {
            get {
                return ResourceManager.GetString("game_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove game.
        /// </summary>
        public static string gameRemoval {
            get {
                return ResourceManager.GetString("gameRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All saves restore.
        /// </summary>
        public static string gamesRestoring {
            get {
                return ResourceManager.GetString("gamesRestoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All saves backup.
        /// </summary>
        public static string gamesSaving {
            get {
                return ResourceManager.GetString("gamesSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image not found..
        /// </summary>
        public static string image_not_found {
            get {
                return ResourceManager.GetString("image_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Images.
        /// </summary>
        public static string images_type {
            get {
                return ResourceManager.GetString("images_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saves folder not found..
        /// </summary>
        public static string no_save_folder {
            get {
                return ResourceManager.GetString("no_save_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open saves folder.
        /// </summary>
        public static string open_saves_folder {
            get {
                return ResourceManager.GetString("open_saves_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove game.
        /// </summary>
        public static string remove_game {
            get {
                return ResourceManager.GetString("remove_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restore.
        /// </summary>
        public static string restore {
            get {
                return ResourceManager.GetString("restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restore all.
        /// </summary>
        public static string restore_all {
            get {
                return ResourceManager.GetString("restore_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saves Manager.
        /// </summary>
        public static string saves_manager {
            get {
                return ResourceManager.GetString("saves_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saves path:.
        /// </summary>
        public static string saves_path {
            get {
                return ResourceManager.GetString("saves_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort list.
        /// </summary>
        public static string sort_games {
            get {
                return ResourceManager.GetString("sort_games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List has been sorted..
        /// </summary>
        public static string sorted {
            get {
                return ResourceManager.GetString("sorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restored successfully..
        /// </summary>
        public static string successfully_restored {
            get {
                return ResourceManager.GetString("successfully_restored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Backup was successfull..
        /// </summary>
        public static string successfully_saved {
            get {
                return ResourceManager.GetString("successfully_saved", resourceCulture);
            }
        }
    }
}
